/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Colibri design token — Material You palette (Serenity / Sage Green)
        'surface':                   '#fbf9f8',
        'surface-dim':               '#dbd9d9',
        'surface-bright':            '#fbf9f8',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f5f3f3',
        'surface-container':         '#efeded',
        'surface-container-high':    '#eae8e7',
        'surface-container-highest': '#e4e2e2',
        'surface-variant':           '#e4e2e2',
        'surface-tint':              '#4f6356',
        'on-surface':                '#1b1c1c',
        'on-surface-variant':        '#434843',
        'inverse-surface':           '#303030',
        'inverse-on-surface':        '#f2f0f0',
        'background':                '#fbf9f8',
        'on-background':             '#1b1c1c',
        'outline':                   '#737873',
        'outline-variant':           '#c3c8c2',
        'primary':                   '#4f6356',
        'on-primary':                '#ffffff',
        'primary-container':         '#d1e7d6',
        'on-primary-container':      '#55685b',
        'primary-fixed':             '#d2e8d7',
        'primary-fixed-dim':         '#b6ccbb',
        'on-primary-fixed':          '#0d1f15',
        'on-primary-fixed-variant':  '#384b3f',
        'inverse-primary':           '#b6ccbb',
        'secondary':                 '#5e5f5b',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#e3e3de',
        'on-secondary-container':    '#646561',
        'secondary-fixed':           '#e3e3de',
        'secondary-fixed-dim':       '#c7c7c2',
        'on-secondary-fixed':        '#1b1c19',
        'on-secondary-fixed-variant':'#464744',
        'tertiary':                  '#4b6453',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#cce8d3',
        'on-tertiary-container':     '#516958',
        'tertiary-fixed':            '#cee9d4',
        'tertiary-fixed-dim':        '#b2cdb9',
        'on-tertiary-fixed':         '#082013',
        'on-tertiary-fixed-variant': '#344c3d',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body:     ['"Atkinson Hyperlegible Next"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':     ['20px', { lineHeight: '32px', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-md':     ['18px', { lineHeight: '28px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        sm:      '0.5rem',
        DEFAULT: '1rem',
        md:      '1.5rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      spacing: {
        'unit':                     '8px',
        'stack-gap-sm':             '12px',
        'stack-gap-md':             '24px',
        'stack-gap-lg':             '48px',
        'container-padding-mobile': '24px',
        'container-padding-desktop':'64px',
      },
      boxShadow: {
        soft: '0 10px 40px 0 rgba(209, 231, 214, 0.25)',
        'soft-hover': '0 20px 50px 0 rgba(209, 231, 214, 0.45)',
      },
    },
  },
  plugins: [],
}
